### ISSUE TITLE
Compatible with TYPO3 v9?

### ISSUE THREAD

**Issue by bendoo** [in2code-de/in2connector#1]
Hello,
Any chance that this extension will work with TYPO3 9.x?
Please let me know!

Thanks and regards,

**Comment by vertexvaar** [comment]
Hi @bendoo,

we haven't planned a compatibility upgrade, yet.
The only place where we require this ext is a TYPO3 v8 project, which will probably stay v8 eLTS as long as possible.
However, you are welcome to open a pull request or get in contact with info@in2code.de if you want to sponsor an upgrade.

with regards
